package frc.robot.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

import frc.robot.interfaces.*;
import frc.robot.Ports;


// a class to raise the outer/main drivetrain (by lowering the inner/mini drivetrain)
public class Ejector extends Subsystem implements IEjector{
	
	static final int WAIT_MS = 1000;
	
	DoubleSolenoid inout;


	public Ejector() {
		// the double solenoid valve will send compressed air from the tank wherever needed
		inout = new DoubleSolenoid(Ports.CAN.PCM, Ports.PCM.EJECTOR_RETRACTED, Ports.PCM.EJECTOR_EXTENDED); // make sure ports are properly sets in Ports.java	
	}
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

	public void setPosition(Position pos)
	{
		switch(pos)
		{
			case RETRACTED:
			{
				inout.set(DoubleSolenoid.Value.kReverse); // adjust direction if needed
				break;
			}
			case EXTENDED:
			{
				inout.set(DoubleSolenoid.Value.kForward); // adjust direction if needed
				break;
			}
			default:
			{
				// do nothing
			}
		}
	}

	public Position getPosition()
	{
		DoubleSolenoid.Value value = inout.get();
		
		switch(value)
		{
			case kReverse:
			{
				return Position.RETRACTED;
			}
			case kForward:
			{
				return Position.EXTENDED;
			}
			default:
			{
				return Position.UNKNOWN;
			}
		}
	}
}
